Console.WriteLine("Введите первое число");
int a = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите второе число");
int b = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите третье число");
int c = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("А = " + a + " B = " + b + " С = " + c);
int[] Numbers = {a, b, c};
int maxValue = Numbers.Max<int>();
Console.WriteLine("Max = " +maxValue);
